apiVersion: v1  
kind: Pod
metadata:
  name: emptydir-demo
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
    - name: almalinux
      image: almalinux:9
      volumeMounts:
        - name: nginx-logs
          mountPath: /mnt/nginx-logs
          readonly: true

  volumes:
    - name: nginx-logs
      emptyDir:
        sizeLimit: 100Mi