apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    project: roboshop
    component: frontend
    environment: dev
    version: v1
spec: 
  containers:
    - name: nginx
      image: nginx