apiVersion: v1
kind: Service
metadata: 
  name: nodeport
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environment: dev
    cloud: AWS
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009