apiVersion: v1
kind: Service
metadata: 
  name: nodeport
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    environment: dev
    cloud: AWS
    duration: 1month
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008