apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    purpose: replicaset-demo
    project: rorboshop
spec:
  replicas: 4
  selector:
    matchLabels:
      purpose: replicaset-demo
      project: rorboshop
  template:
    metadata:
      labels:
        purpose: replicaset-demo
        project: rorboshop
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-demo
spec:
  type : LoadBalancer
  selector:
    purpose: replicaset-demo
    project: rorboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
