apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  clusterIp: None
  selector: 
    purpose: headlessservice-demo
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-service-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      purpose: headlessservice-demo
  template:
    metadata:
      name: nginx
      labels:
        purpose: headlessservice-demo
    spec:
      containers:
        - name: nginx
          image: nginx